# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profiler', '0001_initial'),
        ('Course', '0005_coursegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('totalCredits', models.PositiveIntegerField()),
                ('totalScore', models.DecimalField(decimal_places=1, max_digits=4)),
                ('locked', models.BooleanField(default=0)),
                ('student', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('endMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('marksObtained', models.DecimalField(decimal_places=1, max_digits=4)),
                ('creditsGained', models.PositiveIntegerField()),
                ('course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('student', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Student')),
            ],
        ),
    ]
