# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='totalScore',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='score',
            name='creditsGained',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='endMarks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='score',
            name='marksObtained',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='score',
            name='sessMarks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
