# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_auto_20160509_0144'),
        ('Assessment', '0002_auto_20160509_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('deadline', models.DateField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('publishedDate', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='totalCredits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='totalScore',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
