# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0003_auto_20160509_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
