# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiler', '0002_auto_20160509_0143'),
        ('Assessment', '0004_auto_20160509_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseLink', models.URLField()),
                ('grade', models.CharField(max_length=2, null=True)),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Not Submitted'), (1, 'Submitted'), (2, 'Evaluated')], default=0)),
                ('assignment', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Assessment.Assignment')),
                ('student', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentResponseManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
