# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0005_assignmentresponse_assignmentresponsemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentResponseManager',
        ),
    ]
