# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=20)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Text Book'), (1, 'Reference Book')])),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
    ]
