# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0002_document_publication_resource_weblink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='updatedBy',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Faculty'),
        ),
    ]
