# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branchName', models.CharField(max_length=100)),
                ('seatsAvailable', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('courseType', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
                ('sessMaxMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('endMaxSemMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('maxMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('minPassingMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('semester', models.IntegerField()),
                ('branch', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreeCode', models.CharField(max_length=10)),
                ('degreeName', models.CharField(max_length=30)),
                ('degreeType', models.CharField(max_length=10)),
                ('duration', models.PositiveIntegerField()),
                ('maxCredit', models.PositiveIntegerField()),
                ('annualFee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lateFine', models.DecimalField(decimal_places=2, max_digits=8)),
                ('admissionFee', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=50)),
                ('hod', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('branchCount', models.PositiveIntegerField()),
                ('studentStrength', models.PositiveIntegerField()),
                ('facultyStrength', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('labCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('labName', models.CharField(max_length=100)),
                ('incharge', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('dept', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Degree'),
        ),
        migrations.AddField(
            model_name='branch',
            name='degree',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Degree'),
        ),
        migrations.AddField(
            model_name='branch',
            name='department',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Department'),
        ),
    ]
