# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('batchType', models.CharField(max_length=5)),
                ('strength', models.PositiveIntegerField()),
                ('degree', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Degree')),
                ('department', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Department')),
            ],
        ),
    ]
