# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveIntegerField(),
        ),
    ]
