# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiler', '0001_initial'),
        ('Course', '0004_auto_20160410_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('group', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Group')),
                ('instructor', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='Profiler.Faculty')),
            ],
        ),
    ]
