# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_auto_20160420_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='description yet to be added', max_length=1000),
            preserve_default=False,
        ),
    ]
