# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.CharField(max_length=50),
        ),
    ]
