# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('courseType', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
                ('sessionalMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('endSemMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('maxMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('minPassingMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
