# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='endSemMarks',
            new_name='endMaxSemMarks',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='sessionalMarks',
            new_name='sessMaxMarks',
        ),
    ]
