# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20151228_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyId', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('dateOfJoining', models.DateField()),
                ('jobType', models.CharField(max_length=50)),
                ('dtuRegID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libraryId', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('preferredName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('dtuRegId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('personalMobile', models.IntegerField()),
                ('alternativeMobile', models.IntegerField()),
                ('personalEmail', models.EmailField(max_length=254)),
                ('alternativeEmail', models.EmailField(max_length=254)),
                ('dateOfBirth', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=3)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('dormitory', models.BooleanField()),
                ('photo', models.BinaryField()),
                ('signature', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyId', models.CharField(max_length=100)),
                ('fieldName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollNo', models.CharField(max_length=30)),
                ('dtuRegId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('admissionYear', models.IntegerField()),
                ('passingYear', models.IntegerField()),
                ('libraryId', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
