# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0006_auto_20160410_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('dateAndTime', models.DateTimeField(auto_now=True)),
                ('courseGroup', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.CourseGroup')),
            ],
        ),
    ]
