# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.Branch'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.Degree'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.Department'),
        ),
    ]
