# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiler', '0001_initial'),
        ('NewsFeed', '0003_auto_20160410_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=4000)),
                ('image', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('publishedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_published_by', to='Profiler.Name')),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='fileLink',
            field=models.URLField(default=False),
        ),
    ]
