# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
