# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0006_auto_20160411_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='fb', max_length=500),
            preserve_default=False,
        ),
    ]
