# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('dtuRegId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('personalEmail', models.EmailField(default=False, max_length=254)),
                ('alternativeEmail', models.EmailField(default=False, max_length=254)),
                ('dateOfBirth', models.DateField(default=False)),
                ('gender', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=3)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('dormitory', models.BooleanField(default=False)),
                ('photo', models.BinaryField()),
                ('signature', models.BinaryField()),
                ('facultyId', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('dateOfJoining', models.DateField()),
                ('jobType', models.CharField(max_length=50)),
                ('libraryId', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.PositiveIntegerField()),
                ('mobileNum', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('preferredName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('dtuRegId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('personalEmail', models.EmailField(default=False, max_length=254)),
                ('alternativeEmail', models.EmailField(default=False, max_length=254)),
                ('dateOfBirth', models.DateField(default=False)),
                ('gender', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=3)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('dormitory', models.BooleanField(default=False)),
                ('photo', models.BinaryField()),
                ('signature', models.BinaryField()),
                ('rollNo', models.CharField(max_length=30)),
                ('admissionYear', models.PositiveIntegerField()),
                ('graduationYear', models.PositiveIntegerField()),
                ('libraryId', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(max_length=100)),
                ('alternativeMobile', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_alternative_mobile', to='Profiler.Mobile')),
                ('branch', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Branch')),
                ('degree', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Degree')),
                ('fatherName', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_father_name', to='Profiler.Name')),
                ('guardianAdd', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_guardian_address', to='Profiler.Address')),
                ('motherName', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_mother_name', to='Profiler.Name')),
                ('name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='Profiler.Name')),
                ('permanentAdd', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_permanent_address', to='Profiler.Address')),
                ('personalMobile', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_personal_mobile', to='Profiler.Mobile')),
                ('presentAdd', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_present_address', to='Profiler.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='alternativeMobile',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_alternative_mobile', to='Profiler.Mobile'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Course.Department'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='fatherName',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_father_name', to='Profiler.Name'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='guardianAdd',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_guardian_address', to='Profiler.Address'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='motherName',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_mother_name', to='Profiler.Name'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_name', to='Profiler.Name'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='permanentAdd',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_permanent_address', to='Profiler.Address'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='personalMobile',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_personal_mobile', to='Profiler.Mobile'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='presentAdd',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_present_address', to='Profiler.Address'),
        ),
    ]
