# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dtuRegId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='dtuRegId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
