# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiler', '0002_auto_20160509_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StudentField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='field',
            name='fieldName',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.CharField(choices=[('MAJ', 'Major'), ('MIN', 'Minor'), ('RES', 'Research'), ('INT', 'Intern'), ('TRA', 'Training'), ('OTH', 'Other')], default='OTH', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillName',
            field=models.SlugField(max_length=200),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='skill',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Skill'),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='student',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Student'),
        ),
        migrations.AddField(
            model_name='studentfield',
            name='field',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Field'),
        ),
        migrations.AddField(
            model_name='studentfield',
            name='student',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Student'),
        ),
        migrations.AddField(
            model_name='facultyfield',
            name='field',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Field'),
        ),
    ]
